### ISSUE TITLE
SqLite breaks the project

### ISSUE THREAD

**Issue by FransdeJong** [umbraco/Umbraco.Engage.Issues#5]
We are running SqLite locally on all our cloud projects. 
When we install Engage it breaks our project.

The ideal solution would be supporting SqLite since it's the default database provider of Umbraco.
A less ideal but workable solution would be to detects SqLite and prevent running Engage so the project can still run locally.

Is SqLite support on the horizon?

**Comment by tommel-dev** [comment]
Unfortunately we currently do not support SQLite.

We will start the investigation if you can run/install the site locally but with Engage disabled / uninstalled.

Locally you can run Cloud projects with Engage but the advice is to use SQL Express and/or SQL Server Developer Edition.

**Comment by FransdeJong** [comment]
The default database for a local Umbraco project is SqLite. It would be great if Engage would also offer that functionality and be in line with all the other Umbraco Products.
I think Commerce solved this same issue in the past.

The requirement of using SQLExpress blocks cross platform support and we have to setup a dev server specially for using Engage (we run Macbooks since V13).

Making the project buildable without forcing SQL Express would be a nice first step but getting Engage in line with the other products in the Umbraco Suite would be the best solution in my opinion.

**Comment by TvGessel** [comment]
The temporary (SQLite without Engage active) and the structural solution (SQLite support) are on our backlog for investigation and possibly implementation. Unfortunately I can't give any ETA's now. For the time being the proposed work-around (SQL Express) is the best solution for now.

**Comment by FransdeJong** [comment]
@TvGessel 
The workaround doesn't exist... SQL express is Windows only...

**Comment by TvGessel** [comment]
You could use a separate Windows server or use a separate Azure SQL S0 developer instance which is probably easier in your case.

**Comment by FransdeJong** [comment]
Yeah, possibly. Doesn't feel like the Umbraco Cloud way of working.
Looking forward for a more permanent solution that brings Engage in line with the rest of the Umbraco product range.

**Comment by TvGessel** [comment]
Agree, but we are working on it! The temporary (SQLite without Engage active) and the structural solution (SQLite support) are on our backlog for investigation and possibly implementation. We will keep you informed about the solution and possible timelines.

**Comment by ronaldbarendse** [comment]
Just to give an option that can be used as temporary workaround:

> You can use `<PackageReference Include="Umbraco.Engage" Version="13.1.0" Condition="'$(Configuration)' != 'Debug'" />` to not reference the package when running the site in debug configuration (e.g. locally).

This might break if you're referencing this package in code though (like interfaces, extension methods, etc.)... I did look into using the [`DisableComposer` assembly attribute](https://docs.umbraco.com/umbraco-cms/13.latest/implementation/composing#disablecomposer-and-disable), so you can keep the reference, but disable the automatic service configuration. Unfortunately, this doesn't work, as some composers in Engage are internal and therefore can't be disabled externally... Besides that, not registering the services might still cause issues due to the backoffice UI files (static assets) still being copied into the project and trying to get data from controllers that don't have all required services registered in DI. This could be fixed by registering dummy/no-op services that implement the used interfaces, which might be quite a few.
